### ISSUE TITLE
程序如何控制删除url缓存

### ISSUE THREAD

**Issue by armyhcz** [hertz-contrib/cache#9]
采用如下方式设置url缓存
```
memoryStore := persist.NewMemoryStore(1 * time.Minute)
h.Use(cache.NewCacheByRequestURI(memoryStore, 2*time.Second))
```
-----
现业务存在一种场景
get(获取配置列表)->delete(删除一个配置)->get(刷新列表,更新最新数据)
由于两次get请求间隔时间很短,就造成了删除数据成功之后,刷新列表,接口命中缓存,数据无变化.

------
有什么方式能帮助我解决上面的问题?
或者是否存在自动配置,按照RESTful api的格式,delete发起请求的时候清除对应的get路由缓存

**Comment by li-jin-gou** [comment]
可以考虑使用 Redis 缓存，直接构造 key 删掉 Redis 缓存 ，local-cache 不适合这种场景。

**Comment by armyhcz** [comment]
ok
